### PR TITLE
Update config.lua

### PR DESCRIPTION
**Pull request by lze3**
:@ why capitalise every single word?? lol

### CODE REVIEW

**Comment by OfficialDarkzy** [comment]
Because It Makes It Look Better And Stand Out. Stop Being A Gammer Nazi... K Thx

**Comment by lze3** [comment]
😠

**Comment by lze3** [comment]
wat?? It doesn't look better at all.

**Comment by FAXES** [comment]
This is the main reason its in the config, so you can change it, as Darkzy said it can be more readable and serves a purpose in grammar:


 The general rules for capitalizing words in document titles set out in The Chicago Manual of Style.

1. Always capitalize the first and the last word.
2. Capitalize all nouns, pronouns, adjectives, verbs, adverbs, and subordinate conjunctions ("as", "because", "although").
3. Lowercase all articles, coordinate conjunctions ("and", "or", "nor"), and prepositions regardless of length, when they are other than the first or last word.
4. Lowercase the "to" in an infinitive.
_Source: Writers Block Writing_

So its in the config for you to edit...

**Pull request closed without merging**
